---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/posts
  label: Content
  create: all
  match: "**/*"
  new_doc_ext: md
upload_dir: ''
public_path: https://res.cloudinary.com/lauragift/image/upload
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_command: gridsome build
  publish_command: vuepress build -d .vuepress/dist
  preview_output_directory: public
  output_directory: ".vuepress/dist"
